version: '3'

services:
  mysql:
    image: mysql:5.7.18
    environment:
      MYSQL_ROOT_PASSWORD: BEE38DF8AA2040C4
    volumes:
      - "./test/resource:/docker-entrypoint-initdb.d"
    ports:
      - "33060:3306"
